#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.16
# In conjunction with Tcl version 8.6
#    Aug 29, 2018 10:54:24 AM IST


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *
    from tkinter import filedialog
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import config    

def on_load_model():
    print('detector_gui_support.on_load_model')    
    sys.stdout.flush()

def on_set_video_source():
    print('detector_gui_support.on_set_video_source')
    if py3:
        top_level.filename =  filedialog.askopenfilename(initialdir = "/",title = "Select file",filetypes = (("mp4 files","*.mp4"), ("avi files","*.avi") ,("all files","*.*")))
        print("VIDEO SOURCE CHANGED", top_level.filename)
        if top_level.filename!= "": config.set_video_source(top_level.filename)
    sys.stdout.flush()

def on_start():
    print('detector_gui_support.on_start')
    w.started= True    
    w.delay = 10
    w.update()
    sys.stdout.flush()

def on_stop():
    print('detector_gui_support.on_stop')
    w.restart_video()
    w.started= False
    sys.stdout.flush()

def on_pause():
    print('detector_gui_support.on_pause')
    w.started= False
    sys.stdout.flush()    

def on_history():
    print('detector_gui_support.on_history')
    sys.stdout.flush()  

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import detector
    detector.vp_start_gui()


